### ISSUE TITLE
BibEdit: Further improvements of Authority Records in record editor

### ISSUE THREAD

**Issue by audub** [tind/invenio-fork#31]
A couple of more issues from Kenneth on ASANA: 

- [ ] Better way to handle indicators in Record Editor
Right now you have to specify which marc fields the different categories (Person, Subject, Geographical) should work for in Record Editor. Example, you should be able to add the 100 field from the authority record (Author name) into 100%%a and 700%%a of the bibliographic record. As default, it only worked for 100__a and 700__a. Therefore Guillaume added 10012a, 1001_a, 70012a, 7001_a etc. for the the indicators that we saw existed in their existing records. Not all combinations of indicators are therefore defined. 

Either we have to add a bunch of combinations or enable the use of wildcards (%%) in record editor.

- [ ] Be able to search for more than header, and insert the header as the result
The attached picture shows a typical authorioty record for regular subjects. You have the header in 150 and different variants in 450. Right now it is only possible use the auto-completion on the header. Ideally, you should be able to start writing and the auto-completion function should query both the header and the 450 field. If he finds "ADMINISTRADORES DE EDUCACIÓN" and you select it, it should fill in the main field "EDUCATIONAL ADMINISTRATORS"

**Comment by PXke** [comment]
Point 2 does it mean that if the guy click on ADMINISTRADORES DE EDUCACIÓN it should write EDUCATIONAL ADMINISTRATORS, isn't it quite counter intuitive ?

**Comment by audub** [comment]
I think he means that it is good for productiveness. This is not to be done now anyway. We can discuss it with Kenneth at a later point. I can remove you from the assignee, so you dont get confused on what to do :p

**Comment by Kennethhole** [comment]
Yes @PXke that is what I meant. Next version ;)

I see room for one more improvement. Still, I want us to employ what we already have to OHCHR before we start on this work. And I guess we will get some feedback from her on things that does not work 100%, which will be as important. Anyway:

If you add a new field and regret, there is no easy way to delete it. You first have to fill out the field, so that it get a select box. First then can you choose to remove the field. If you try to submit without deleting it, you get the message as below. Therefore, it would be good with a delete-button next to each field. At least before you get a select box.

![screenshot 2015-04-08 10 55 51](https://cloud.githubusercontent.com/assets/6758333/7042042/fd992776-ddde-11e4-911c-73427e82850d.png)

**Comment by blixhavn** [comment]
This issue was moved to tind/invenio#3
